workspace:
  base: /vue43

pipeline:
  docker:
    image: plugins/docker
    repo: evetools/vue43
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:8}
